/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CoreWriterLib,
  CoreWriterLibInterface,
} from "../../../../lib/hyper-evm-lib/src/CoreWriterLib";

const _abi = [
  {
    inputs: [],
    name: "CoreWriterLib__CannotSelfTransfer",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "CoreWriterLib__CoreAmountTooLarge",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "CoreWriterLib__EvmAmountTooSmall",
    type: "error",
  },
  {
    inputs: [],
    name: "CoreWriterLib__HypeTransferFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "lockedUntilTimestamp",
        type: "uint64",
      },
    ],
    name: "CoreWriterLib__StillLockedUntilTimestamp",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220050fd00b9675945d76b66d9d91a0f6668789bcdac8dd52dd8d1b2d56ed39e1f364736f6c63430008130033";

type CoreWriterLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CoreWriterLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CoreWriterLib__factory extends ContractFactory {
  constructor(...args: CoreWriterLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CoreWriterLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CoreWriterLib__factory {
    return super.connect(runner) as CoreWriterLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CoreWriterLibInterface {
    return new Interface(_abi) as CoreWriterLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CoreWriterLib {
    return new Contract(address, _abi, runner) as unknown as CoreWriterLib;
  }
}
