/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  PrecompileLib,
  PrecompileLibInterface,
} from "../../../../lib/hyper-evm-lib/src/PrecompileLib";

const _abi = [
  {
    inputs: [],
    name: "PrecompileLib__AccountMarginSummaryPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__BboPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__CoreUserExistsPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__DelegationsPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__DelegatorSummaryPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__L1BlockNumberPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__MarkPxPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__OraclePxPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__PerpAssetInfoPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__PositionPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__SpotBalancePrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__SpotIndexNotFound",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__SpotInfoPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__SpotPxPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__TokenInfoPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__TokenSupplyPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__VaultEquityPrecompileFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "PrecompileLib__WithdrawablePrecompileFailed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d5adf567a8812f430ac9d17b7b637b98891126f25f63a5e207d270b9276e257e64736f6c63430008130033";

type PrecompileLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PrecompileLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PrecompileLib__factory extends ContractFactory {
  constructor(...args: PrecompileLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PrecompileLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PrecompileLib__factory {
    return super.connect(runner) as PrecompileLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PrecompileLibInterface {
    return new Interface(_abi) as PrecompileLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PrecompileLib {
    return new Contract(address, _abi, runner) as unknown as PrecompileLib;
  }
}
