/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  L1OracleAdapter,
  L1OracleAdapterInterface,
} from "../../../src/libraries/L1OracleAdapter";

const _abi = [
  {
    inputs: [],
    name: "L1OracleAdapter__PrecompileCallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "L1OracleAdapter__StalePrice",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220742aa782e562c11ea4e8f479ac5c9c49944293e5c7bbee1cd244aa3f07a085ee64736f6c63430008130033";

type L1OracleAdapterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: L1OracleAdapterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class L1OracleAdapter__factory extends ContractFactory {
  constructor(...args: L1OracleAdapterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      L1OracleAdapter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): L1OracleAdapter__factory {
    return super.connect(runner) as L1OracleAdapter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): L1OracleAdapterInterface {
    return new Interface(_abi) as L1OracleAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): L1OracleAdapter {
    return new Contract(address, _abi, runner) as unknown as L1OracleAdapter;
  }
}
