/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TwoSpeedEWMA,
  TwoSpeedEWMAInterface,
} from "../../../src/libraries/TwoSpeedEWMA";

const _abi = [
  {
    inputs: [],
    name: "TwoSpeedEWMA__InvalidAlpha",
    type: "error",
  },
  {
    inputs: [],
    name: "TwoSpeedEWMA__NotInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "TwoSpeedEWMA__ZeroPrice",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122098110ff5e56d610d8c140a20ad24b3b0cc3c2a63557665e275832e2dd186b85164736f6c63430008130033";

type TwoSpeedEWMAConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TwoSpeedEWMAConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TwoSpeedEWMA__factory extends ContractFactory {
  constructor(...args: TwoSpeedEWMAConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TwoSpeedEWMA & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TwoSpeedEWMA__factory {
    return super.connect(runner) as TwoSpeedEWMA__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TwoSpeedEWMAInterface {
    return new Interface(_abi) as TwoSpeedEWMAInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TwoSpeedEWMA {
    return new Contract(address, _abi, runner) as unknown as TwoSpeedEWMA;
  }
}
