/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  YieldTracker,
  YieldTrackerInterface,
} from "../../../src/libraries/YieldTracker";

const _abi = [
  {
    inputs: [],
    name: "YieldTracker__NotInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "YieldTracker__PeriodTooShort",
    type: "error",
  },
  {
    inputs: [],
    name: "YieldTracker__ZeroLiquidity",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b0a6ea9641c6f969525e5596c8384323368934a4f9aa09684e2b89f72f7937da64736f6c63430008130033";

type YieldTrackerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: YieldTrackerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class YieldTracker__factory extends ContractFactory {
  constructor(...args: YieldTrackerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      YieldTracker & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): YieldTracker__factory {
    return super.connect(runner) as YieldTracker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): YieldTrackerInterface {
    return new Interface(_abi) as YieldTrackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): YieldTracker {
    return new Contract(address, _abi, runner) as unknown as YieldTracker;
  }
}
