/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  HLConstants,
  HLConstantsInterface,
} from "../../../../../lib/hyper-evm-lib/src/common/HLConstants";

const _abi = [
  {
    inputs: [],
    name: "LIMIT_ORDER_TIF_ALO",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LIMIT_ORDER_TIF_GTC",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LIMIT_ORDER_TIF_IOC",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60ad610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c80630eca611f14604c57806337041c8d146069578063fcd2a5f5146070575b600080fd5b6053600381565b60405160ff909116815260200160405180910390f35b6053600181565b605360028156fea2646970667358221220cc01cbb74fb9515f9fedbb340ead5ee054c3ca28572f42bd378aaa8f17ec35bb64736f6c63430008130033";

type HLConstantsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HLConstantsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HLConstants__factory extends ContractFactory {
  constructor(...args: HLConstantsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      HLConstants & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): HLConstants__factory {
    return super.connect(runner) as HLConstants__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HLConstantsInterface {
    return new Interface(_abi) as HLConstantsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): HLConstants {
    return new Contract(address, _abi, runner) as unknown as HLConstants;
  }
}
