/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  HLConversions,
  HLConversionsInterface,
} from "../../../../../lib/hyper-evm-lib/src/common/HLConversions";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "token",
        type: "uint64",
      },
    ],
    name: "HLConversions__InvalidToken",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220238f25e0b9c210e0ecca28ff416ee90096a0a27774a2f423be56bdebe6a03a2464736f6c63430008130033";

type HLConversionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HLConversionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HLConversions__factory extends ContractFactory {
  constructor(...args: HLConversionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      HLConversions & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): HLConversions__factory {
    return super.connect(runner) as HLConversions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HLConversionsInterface {
    return new Interface(_abi) as HLConversionsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HLConversions {
    return new Contract(address, _abi, runner) as unknown as HLConversions;
  }
}
