/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ALMLiquidityQuoteInputStruct = {
  isZeroToOne: boolean;
  amountInMinusFee: BigNumberish;
  feeInBips: BigNumberish;
  sender: AddressLike;
  recipient: AddressLike;
  tokenOutSwap: AddressLike;
};

export type ALMLiquidityQuoteInputStructOutput = [
  isZeroToOne: boolean,
  amountInMinusFee: bigint,
  feeInBips: bigint,
  sender: string,
  recipient: string,
  tokenOutSwap: string
] & {
  isZeroToOne: boolean;
  amountInMinusFee: bigint;
  feeInBips: bigint;
  sender: string;
  recipient: string;
  tokenOutSwap: string;
};

export type ALMLiquidityQuoteStruct = {
  isCallbackOnSwap: boolean;
  amountOut: BigNumberish;
  amountInFilled: BigNumberish;
};

export type ALMLiquidityQuoteStructOutput = [
  isCallbackOnSwap: boolean,
  amountOut: bigint,
  amountInFilled: bigint
] & { isCallbackOnSwap: boolean; amountOut: bigint; amountInFilled: bigint };

export declare namespace TwoSpeedEWMA {
  export type VolatilityReadingStruct = {
    fastEWMA: BigNumberish;
    slowEWMA: BigNumberish;
    fastVar: BigNumberish;
    slowVar: BigNumberish;
    deviationBps: BigNumberish;
    isVolatile: boolean;
  };

  export type VolatilityReadingStructOutput = [
    fastEWMA: bigint,
    slowEWMA: bigint,
    fastVar: bigint,
    slowVar: bigint,
    deviationBps: bigint,
    isVolatile: boolean
  ] & {
    fastEWMA: bigint;
    slowEWMA: bigint;
    fastVar: bigint;
    slowVar: bigint;
    deviationBps: bigint;
    isVolatile: boolean;
  };
}

export interface HLEALMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "accumulatedFees0"
      | "accumulatedFees1"
      | "calculateSpreadDetails"
      | "canTrade"
      | "collectFees"
      | "collectSurplus"
      | "depositLiquidity"
      | "feeRecipient"
      | "forceSetVariance"
      | "getAccumulatedFees"
      | "getLiquidityQuote"
      | "getOracleMidPrice"
      | "getQuote"
      | "getSpread"
      | "getSpreadConfig"
      | "getTotalLiquidity"
      | "getVariance"
      | "getVolatility"
      | "initialize"
      | "initializeEWMA"
      | "initializeWithAlphas"
      | "kImpact"
      | "kVol"
      | "manualPrice"
      | "onDepositLiquidityCallback"
      | "onSwapCallback"
      | "owner"
      | "paused"
      | "pendingOwner"
      | "pool"
      | "previewSwap"
      | "priceEWMA"
      | "renounceOwnership"
      | "setFeeRecipient"
      | "setManualPrice"
      | "setOracleMode"
      | "setPaused"
      | "setSpreadConfig"
      | "setTokenIndices"
      | "setVolatilityThreshold"
      | "setYieldOptimizer"
      | "surplusCaptured0"
      | "surplusCaptured1"
      | "token0"
      | "token0Index"
      | "token1"
      | "token1Index"
      | "transferOwnership"
      | "updateEWMA"
      | "useL1Oracle"
      | "volatilityThresholdBps"
      | "withdrawLiquidity"
      | "yieldOptimizer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesCollected"
      | "LiquidityDeposited"
      | "LiquidityWithdrawn"
      | "ManualPriceSet"
      | "OracleModeSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "SpreadConfigUpdated"
      | "SurplusCollected"
      | "SwapExecuted"
      | "VolatilityGated"
      | "VolatilityThresholdUpdated"
      | "YieldOptimizerSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSpreadDetails",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "canTrade", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectSurplus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositLiquidity",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceSetVariance",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityQuote",
    values: [ALMLiquidityQuoteInputStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleMidPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuote",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpread",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpreadConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVariance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVolatility",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeEWMA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeWithAlphas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "kImpact", values?: undefined): string;
  encodeFunctionData(functionFragment: "kVol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "manualPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onDepositLiquidityCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onSwapCallback",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewSwap",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "priceEWMA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setManualPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleMode",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setSpreadConfig",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenIndices",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVolatilityThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldOptimizer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "surplusCaptured0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "surplusCaptured1",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "token0Index",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "token1Index",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEWMA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "useL1Oracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "volatilityThresholdBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldOptimizer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSpreadDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectSurplus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceSetVariance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleMidPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQuote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSpread", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSpreadConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVariance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVolatility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeEWMA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeWithAlphas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kImpact", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kVol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDepositLiquidityCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onSwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceEWMA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManualPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSpreadConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenIndices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVolatilityThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldOptimizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surplusCaptured0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surplusCaptured1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "token0Index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "token1Index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateEWMA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "useL1Oracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "volatilityThresholdBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldOptimizer",
    data: BytesLike
  ): Result;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityDepositedEvent {
  export type InputTuple = [
    sender: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [sender: string, amount0: bigint, amount1: bigint];
  export interface OutputObject {
    sender: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWithdrawnEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManualPriceSetEvent {
  export type InputTuple = [price: BigNumberish];
  export type OutputTuple = [price: bigint];
  export interface OutputObject {
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleModeSetEvent {
  export type InputTuple = [useL1Oracle: boolean];
  export type OutputTuple = [useL1Oracle: boolean];
  export interface OutputObject {
    useL1Oracle: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [isPaused: boolean];
  export type OutputTuple = [isPaused: boolean];
  export interface OutputObject {
    isPaused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpreadConfigUpdatedEvent {
  export type InputTuple = [kVol: BigNumberish, kImpact: BigNumberish];
  export type OutputTuple = [kVol: bigint, kImpact: bigint];
  export interface OutputObject {
    kVol: bigint;
    kImpact: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurplusCollectedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    sender: AddressLike,
    isBuy: boolean,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    oraclePrice: BigNumberish,
    effectivePrice: BigNumberish,
    spreadUsed: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    isBuy: boolean,
    amountIn: bigint,
    amountOut: bigint,
    oraclePrice: bigint,
    effectivePrice: bigint,
    spreadUsed: bigint
  ];
  export interface OutputObject {
    sender: string;
    isBuy: boolean;
    amountIn: bigint;
    amountOut: bigint;
    oraclePrice: bigint;
    effectivePrice: bigint;
    spreadUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VolatilityGatedEvent {
  export type InputTuple = [
    fastEWMA: BigNumberish,
    slowEWMA: BigNumberish,
    deviationBps: BigNumberish,
    thresholdBps: BigNumberish
  ];
  export type OutputTuple = [
    fastEWMA: bigint,
    slowEWMA: bigint,
    deviationBps: bigint,
    thresholdBps: bigint
  ];
  export interface OutputObject {
    fastEWMA: bigint;
    slowEWMA: bigint;
    deviationBps: bigint;
    thresholdBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VolatilityThresholdUpdatedEvent {
  export type InputTuple = [volatilityThresholdBps: BigNumberish];
  export type OutputTuple = [volatilityThresholdBps: bigint];
  export interface OutputObject {
    volatilityThresholdBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldOptimizerSetEvent {
  export type InputTuple = [optimizer: AddressLike];
  export type OutputTuple = [optimizer: string];
  export interface OutputObject {
    optimizer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HLEALM extends BaseContract {
  connect(runner?: ContractRunner | null): HLEALM;
  waitForDeployment(): Promise<this>;

  interface: HLEALMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  accumulatedFees0: TypedContractMethod<[], [bigint], "view">;

  accumulatedFees1: TypedContractMethod<[], [bigint], "view">;

  calculateSpreadDetails: TypedContractMethod<
    [amountIn: BigNumberish, reserveIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        volSpread: bigint;
        impactSpread: bigint;
        totalSpread: bigint;
      }
    ],
    "view"
  >;

  canTrade: TypedContractMethod<[], [boolean], "view">;

  collectFees: TypedContractMethod<[], [void], "nonpayable">;

  collectSurplus: TypedContractMethod<[], [void], "nonpayable">;

  depositLiquidity: TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish, sender: AddressLike],
    [[bigint, bigint] & { amount0Deposited: bigint; amount1Deposited: bigint }],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  forceSetVariance: TypedContractMethod<
    [_fastVar: BigNumberish, _slowVar: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAccumulatedFees: TypedContractMethod<
    [],
    [[bigint, bigint] & { fees0: bigint; fees1: bigint }],
    "view"
  >;

  getLiquidityQuote: TypedContractMethod<
    [
      _almLiquidityQuoteInput: ALMLiquidityQuoteInputStruct,
      arg1: BytesLike,
      arg2: BytesLike
    ],
    [ALMLiquidityQuoteStructOutput],
    "nonpayable"
  >;

  getOracleMidPrice: TypedContractMethod<[], [bigint], "view">;

  getQuote: TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  getSpread: TypedContractMethod<
    [amountIn: BigNumberish, tokenIn: AddressLike],
    [
      [bigint, bigint, bigint] & {
        volSpread: bigint;
        impactSpread: bigint;
        totalSpread: bigint;
      }
    ],
    "view"
  >;

  getSpreadConfig: TypedContractMethod<
    [],
    [[bigint, bigint] & { _kVol: bigint; _kImpact: bigint }],
    "view"
  >;

  getTotalLiquidity: TypedContractMethod<[], [bigint], "view">;

  getVariance: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fastVar: bigint;
        slowVar: bigint;
        maxVar: bigint;
      }
    ],
    "view"
  >;

  getVolatility: TypedContractMethod<
    [],
    [TwoSpeedEWMA.VolatilityReadingStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  initializeEWMA: TypedContractMethod<[], [void], "nonpayable">;

  initializeWithAlphas: TypedContractMethod<
    [fastAlpha: BigNumberish, slowAlpha: BigNumberish],
    [void],
    "nonpayable"
  >;

  kImpact: TypedContractMethod<[], [bigint], "view">;

  kVol: TypedContractMethod<[], [bigint], "view">;

  manualPrice: TypedContractMethod<[], [bigint], "view">;

  onDepositLiquidityCallback: TypedContractMethod<
    [_amount0: BigNumberish, _amount1: BigNumberish, arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  onSwapCallback: TypedContractMethod<
    [arg0: boolean, arg1: BigNumberish, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  previewSwap: TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        amountOut: bigint;
        spreadFee: bigint;
        canExecute: boolean;
      }
    ],
    "view"
  >;

  priceEWMA: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        fastEWMA: bigint;
        slowEWMA: bigint;
        fastVar: bigint;
        slowVar: bigint;
        fastAlpha: bigint;
        slowAlpha: bigint;
        lastUpdateTime: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setManualPrice: TypedContractMethod<
    [_price: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOracleMode: TypedContractMethod<
    [_useL1Oracle: boolean],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  setSpreadConfig: TypedContractMethod<
    [_kVol: BigNumberish, _kImpact: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenIndices: TypedContractMethod<
    [_token0Index: BigNumberish, _token1Index: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVolatilityThreshold: TypedContractMethod<
    [_volatilityThresholdBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setYieldOptimizer: TypedContractMethod<
    [_optimizer: AddressLike],
    [void],
    "nonpayable"
  >;

  surplusCaptured0: TypedContractMethod<[], [bigint], "view">;

  surplusCaptured1: TypedContractMethod<[], [bigint], "view">;

  token0: TypedContractMethod<[], [string], "view">;

  token0Index: TypedContractMethod<[], [bigint], "view">;

  token1: TypedContractMethod<[], [string], "view">;

  token1Index: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEWMA: TypedContractMethod<[], [void], "nonpayable">;

  useL1Oracle: TypedContractMethod<[], [boolean], "view">;

  volatilityThresholdBps: TypedContractMethod<[], [bigint], "view">;

  withdrawLiquidity: TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  yieldOptimizer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "accumulatedFees0"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateSpreadDetails"
  ): TypedContractMethod<
    [amountIn: BigNumberish, reserveIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        volSpread: bigint;
        impactSpread: bigint;
        totalSpread: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "canTrade"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectSurplus"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositLiquidity"
  ): TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish, sender: AddressLike],
    [[bigint, bigint] & { amount0Deposited: bigint; amount1Deposited: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forceSetVariance"
  ): TypedContractMethod<
    [_fastVar: BigNumberish, _slowVar: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAccumulatedFees"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { fees0: bigint; fees1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLiquidityQuote"
  ): TypedContractMethod<
    [
      _almLiquidityQuoteInput: ALMLiquidityQuoteInputStruct,
      arg1: BytesLike,
      arg2: BytesLike
    ],
    [ALMLiquidityQuoteStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOracleMidPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuote"
  ): TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSpread"
  ): TypedContractMethod<
    [amountIn: BigNumberish, tokenIn: AddressLike],
    [
      [bigint, bigint, bigint] & {
        volSpread: bigint;
        impactSpread: bigint;
        totalSpread: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSpreadConfig"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _kVol: bigint; _kImpact: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVariance"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fastVar: bigint;
        slowVar: bigint;
        maxVar: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVolatility"
  ): TypedContractMethod<
    [],
    [TwoSpeedEWMA.VolatilityReadingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeEWMA"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeWithAlphas"
  ): TypedContractMethod<
    [fastAlpha: BigNumberish, slowAlpha: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "kImpact"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "kVol"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onDepositLiquidityCallback"
  ): TypedContractMethod<
    [_amount0: BigNumberish, _amount1: BigNumberish, arg2: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onSwapCallback"
  ): TypedContractMethod<
    [arg0: boolean, arg1: BigNumberish, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewSwap"
  ): TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        amountOut: bigint;
        spreadFee: bigint;
        canExecute: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceEWMA"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        fastEWMA: bigint;
        slowEWMA: bigint;
        fastVar: bigint;
        slowVar: bigint;
        fastAlpha: bigint;
        slowAlpha: bigint;
        lastUpdateTime: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setManualPrice"
  ): TypedContractMethod<[_price: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracleMode"
  ): TypedContractMethod<[_useL1Oracle: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSpreadConfig"
  ): TypedContractMethod<
    [_kVol: BigNumberish, _kImpact: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenIndices"
  ): TypedContractMethod<
    [_token0Index: BigNumberish, _token1Index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVolatilityThreshold"
  ): TypedContractMethod<
    [_volatilityThresholdBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setYieldOptimizer"
  ): TypedContractMethod<[_optimizer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "surplusCaptured0"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "surplusCaptured1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token0Index"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token1Index"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEWMA"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "useL1Oracle"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "volatilityThresholdBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "yieldOptimizer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityDeposited"
  ): TypedContractEvent<
    LiquidityDepositedEvent.InputTuple,
    LiquidityDepositedEvent.OutputTuple,
    LiquidityDepositedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityWithdrawn"
  ): TypedContractEvent<
    LiquidityWithdrawnEvent.InputTuple,
    LiquidityWithdrawnEvent.OutputTuple,
    LiquidityWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ManualPriceSet"
  ): TypedContractEvent<
    ManualPriceSetEvent.InputTuple,
    ManualPriceSetEvent.OutputTuple,
    ManualPriceSetEvent.OutputObject
  >;
  getEvent(
    key: "OracleModeSet"
  ): TypedContractEvent<
    OracleModeSetEvent.InputTuple,
    OracleModeSetEvent.OutputTuple,
    OracleModeSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SpreadConfigUpdated"
  ): TypedContractEvent<
    SpreadConfigUpdatedEvent.InputTuple,
    SpreadConfigUpdatedEvent.OutputTuple,
    SpreadConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SurplusCollected"
  ): TypedContractEvent<
    SurplusCollectedEvent.InputTuple,
    SurplusCollectedEvent.OutputTuple,
    SurplusCollectedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VolatilityGated"
  ): TypedContractEvent<
    VolatilityGatedEvent.InputTuple,
    VolatilityGatedEvent.OutputTuple,
    VolatilityGatedEvent.OutputObject
  >;
  getEvent(
    key: "VolatilityThresholdUpdated"
  ): TypedContractEvent<
    VolatilityThresholdUpdatedEvent.InputTuple,
    VolatilityThresholdUpdatedEvent.OutputTuple,
    VolatilityThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "YieldOptimizerSet"
  ): TypedContractEvent<
    YieldOptimizerSetEvent.InputTuple,
    YieldOptimizerSetEvent.OutputTuple,
    YieldOptimizerSetEvent.OutputObject
  >;

  filters: {
    "FeesCollected(address,uint256,uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "LiquidityDeposited(address,uint256,uint256)": TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
    LiquidityDeposited: TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;

    "LiquidityWithdrawn(address,uint256,uint256)": TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;
    LiquidityWithdrawn: TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;

    "ManualPriceSet(uint256)": TypedContractEvent<
      ManualPriceSetEvent.InputTuple,
      ManualPriceSetEvent.OutputTuple,
      ManualPriceSetEvent.OutputObject
    >;
    ManualPriceSet: TypedContractEvent<
      ManualPriceSetEvent.InputTuple,
      ManualPriceSetEvent.OutputTuple,
      ManualPriceSetEvent.OutputObject
    >;

    "OracleModeSet(bool)": TypedContractEvent<
      OracleModeSetEvent.InputTuple,
      OracleModeSetEvent.OutputTuple,
      OracleModeSetEvent.OutputObject
    >;
    OracleModeSet: TypedContractEvent<
      OracleModeSetEvent.InputTuple,
      OracleModeSetEvent.OutputTuple,
      OracleModeSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SpreadConfigUpdated(uint256,uint256)": TypedContractEvent<
      SpreadConfigUpdatedEvent.InputTuple,
      SpreadConfigUpdatedEvent.OutputTuple,
      SpreadConfigUpdatedEvent.OutputObject
    >;
    SpreadConfigUpdated: TypedContractEvent<
      SpreadConfigUpdatedEvent.InputTuple,
      SpreadConfigUpdatedEvent.OutputTuple,
      SpreadConfigUpdatedEvent.OutputObject
    >;

    "SurplusCollected(address,uint256,uint256)": TypedContractEvent<
      SurplusCollectedEvent.InputTuple,
      SurplusCollectedEvent.OutputTuple,
      SurplusCollectedEvent.OutputObject
    >;
    SurplusCollected: TypedContractEvent<
      SurplusCollectedEvent.InputTuple,
      SurplusCollectedEvent.OutputTuple,
      SurplusCollectedEvent.OutputObject
    >;

    "SwapExecuted(address,bool,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;

    "VolatilityGated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      VolatilityGatedEvent.InputTuple,
      VolatilityGatedEvent.OutputTuple,
      VolatilityGatedEvent.OutputObject
    >;
    VolatilityGated: TypedContractEvent<
      VolatilityGatedEvent.InputTuple,
      VolatilityGatedEvent.OutputTuple,
      VolatilityGatedEvent.OutputObject
    >;

    "VolatilityThresholdUpdated(uint256)": TypedContractEvent<
      VolatilityThresholdUpdatedEvent.InputTuple,
      VolatilityThresholdUpdatedEvent.OutputTuple,
      VolatilityThresholdUpdatedEvent.OutputObject
    >;
    VolatilityThresholdUpdated: TypedContractEvent<
      VolatilityThresholdUpdatedEvent.InputTuple,
      VolatilityThresholdUpdatedEvent.OutputTuple,
      VolatilityThresholdUpdatedEvent.OutputObject
    >;

    "YieldOptimizerSet(address)": TypedContractEvent<
      YieldOptimizerSetEvent.InputTuple,
      YieldOptimizerSetEvent.OutputTuple,
      YieldOptimizerSetEvent.OutputObject
    >;
    YieldOptimizerSet: TypedContractEvent<
      YieldOptimizerSetEvent.InputTuple,
      YieldOptimizerSetEvent.OutputTuple,
      YieldOptimizerSetEvent.OutputObject
    >;
  };
}
