/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2Step__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "HLConstants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HLConstants__factory>;
    getContractFactory(
      name: "HLConversions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HLConversions__factory>;
    getContractFactory(
      name: "CoreWriterLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CoreWriterLib__factory>;
    getContractFactory(
      name: "ICoreDepositWallet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoreDepositWallet__factory>;
    getContractFactory(
      name: "ICoreWriter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoreWriter__factory>;
    getContractFactory(
      name: "ITokenRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITokenRegistry__factory>;
    getContractFactory(
      name: "PrecompileLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrecompileLib__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ISovereignALM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignALM__factory>;
    getContractFactory(
      name: "IFlashBorrower",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlashBorrower__factory>;
    getContractFactory(
      name: "ISovereignPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignPool__factory>;
    getContractFactory(
      name: "IValantisPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IValantisPool__factory>;
    getContractFactory(
      name: "ISwapFeeModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapFeeModule__factory>;
    getContractFactory(
      name: "ISwapFeeModuleMinimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapFeeModuleMinimal__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2Step__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ISovereignALM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignALM__factory>;
    getContractFactory(
      name: "ISovereignOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignOracle__factory>;
    getContractFactory(
      name: "IFlashBorrower",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFlashBorrower__factory>;
    getContractFactory(
      name: "ISovereignPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignPool__factory>;
    getContractFactory(
      name: "ISovereignPoolSwapCallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignPoolSwapCallback__factory>;
    getContractFactory(
      name: "ISovereignVaultMinimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISovereignVaultMinimal__factory>;
    getContractFactory(
      name: "IValantisPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IValantisPool__factory>;
    getContractFactory(
      name: "IVerifierModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifierModule__factory>;
    getContractFactory(
      name: "SovereignPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SovereignPool__factory>;
    getContractFactory(
      name: "ISwapFeeModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapFeeModule__factory>;
    getContractFactory(
      name: "ISwapFeeModuleMinimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapFeeModuleMinimal__factory>;
    getContractFactory(
      name: "Constants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constants__factory>;
    getContractFactory(
      name: "IHLEALM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHLEALM__factory>;
    getContractFactory(
      name: "ILendingModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILendingModule__factory>;
    getContractFactory(
      name: "ILendingOrchestrator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILendingOrchestrator__factory>;
    getContractFactory(
      name: "IOracleModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOracleModule__factory>;
    getContractFactory(
      name: "IQuoteValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IQuoteValidator__factory>;
    getContractFactory(
      name: "IYieldOptimizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IYieldOptimizer__factory>;
    getContractFactory(
      name: "L1OracleAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.L1OracleAdapter__factory>;
    getContractFactory(
      name: "TwoSpeedEWMA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TwoSpeedEWMA__factory>;
    getContractFactory(
      name: "YieldTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldTracker__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "HLEALM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HLEALM__factory>;
    getContractFactory(
      name: "HLEQuoter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HLEQuoter__factory>;
    getContractFactory(
      name: "IHLEALMState",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHLEALMState__factory>;
    getContractFactory(
      name: "ICoreWriter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoreWriter__factory>;
    getContractFactory(
      name: "LendingModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LendingModule__factory>;
    getContractFactory(
      name: "YieldOptimizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldOptimizer__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2Step>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "HLConstants",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HLConstants>;
    getContractAt(
      name: "HLConversions",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HLConversions>;
    getContractAt(
      name: "CoreWriterLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CoreWriterLib>;
    getContractAt(
      name: "ICoreDepositWallet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoreDepositWallet>;
    getContractAt(
      name: "ICoreWriter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoreWriter>;
    getContractAt(
      name: "ITokenRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITokenRegistry>;
    getContractAt(
      name: "PrecompileLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrecompileLib>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ISovereignALM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignALM>;
    getContractAt(
      name: "IFlashBorrower",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlashBorrower>;
    getContractAt(
      name: "ISovereignPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignPool>;
    getContractAt(
      name: "IValantisPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IValantisPool>;
    getContractAt(
      name: "ISwapFeeModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapFeeModule>;
    getContractAt(
      name: "ISwapFeeModuleMinimal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapFeeModuleMinimal>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2Step>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ISovereignALM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignALM>;
    getContractAt(
      name: "ISovereignOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignOracle>;
    getContractAt(
      name: "IFlashBorrower",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFlashBorrower>;
    getContractAt(
      name: "ISovereignPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignPool>;
    getContractAt(
      name: "ISovereignPoolSwapCallback",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignPoolSwapCallback>;
    getContractAt(
      name: "ISovereignVaultMinimal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISovereignVaultMinimal>;
    getContractAt(
      name: "IValantisPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IValantisPool>;
    getContractAt(
      name: "IVerifierModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifierModule>;
    getContractAt(
      name: "SovereignPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SovereignPool>;
    getContractAt(
      name: "ISwapFeeModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapFeeModule>;
    getContractAt(
      name: "ISwapFeeModuleMinimal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapFeeModuleMinimal>;
    getContractAt(
      name: "Constants",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Constants>;
    getContractAt(
      name: "IHLEALM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHLEALM>;
    getContractAt(
      name: "ILendingModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILendingModule>;
    getContractAt(
      name: "ILendingOrchestrator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILendingOrchestrator>;
    getContractAt(
      name: "IOracleModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IOracleModule>;
    getContractAt(
      name: "IQuoteValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IQuoteValidator>;
    getContractAt(
      name: "IYieldOptimizer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IYieldOptimizer>;
    getContractAt(
      name: "L1OracleAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.L1OracleAdapter>;
    getContractAt(
      name: "TwoSpeedEWMA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TwoSpeedEWMA>;
    getContractAt(
      name: "YieldTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldTracker>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "HLEALM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HLEALM>;
    getContractAt(
      name: "HLEQuoter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HLEQuoter>;
    getContractAt(
      name: "IHLEALMState",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHLEALMState>;
    getContractAt(
      name: "ICoreWriter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoreWriter>;
    getContractAt(
      name: "LendingModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LendingModule>;
    getContractAt(
      name: "YieldOptimizer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldOptimizer>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "HLConstants",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLConstants>;
    deployContract(
      name: "HLConversions",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLConversions>;
    deployContract(
      name: "CoreWriterLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CoreWriterLib>;
    deployContract(
      name: "ICoreDepositWallet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreDepositWallet>;
    deployContract(
      name: "ICoreWriter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreWriter>;
    deployContract(
      name: "ITokenRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenRegistry>;
    deployContract(
      name: "PrecompileLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrecompileLib>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISovereignALM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignALM>;
    deployContract(
      name: "IFlashBorrower",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlashBorrower>;
    deployContract(
      name: "ISovereignPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignPool>;
    deployContract(
      name: "IValantisPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IValantisPool>;
    deployContract(
      name: "ISwapFeeModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModule>;
    deployContract(
      name: "ISwapFeeModuleMinimal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModuleMinimal>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISovereignALM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignALM>;
    deployContract(
      name: "ISovereignOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignOracle>;
    deployContract(
      name: "IFlashBorrower",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlashBorrower>;
    deployContract(
      name: "ISovereignPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignPool>;
    deployContract(
      name: "ISovereignPoolSwapCallback",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignPoolSwapCallback>;
    deployContract(
      name: "ISovereignVaultMinimal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignVaultMinimal>;
    deployContract(
      name: "IValantisPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IValantisPool>;
    deployContract(
      name: "IVerifierModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifierModule>;
    deployContract(
      name: "SovereignPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SovereignPool>;
    deployContract(
      name: "ISwapFeeModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModule>;
    deployContract(
      name: "ISwapFeeModuleMinimal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModuleMinimal>;
    deployContract(
      name: "Constants",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Constants>;
    deployContract(
      name: "IHLEALM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHLEALM>;
    deployContract(
      name: "ILendingModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILendingModule>;
    deployContract(
      name: "ILendingOrchestrator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILendingOrchestrator>;
    deployContract(
      name: "IOracleModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOracleModule>;
    deployContract(
      name: "IQuoteValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IQuoteValidator>;
    deployContract(
      name: "IYieldOptimizer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldOptimizer>;
    deployContract(
      name: "L1OracleAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.L1OracleAdapter>;
    deployContract(
      name: "TwoSpeedEWMA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TwoSpeedEWMA>;
    deployContract(
      name: "YieldTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldTracker>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "HLEALM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLEALM>;
    deployContract(
      name: "HLEQuoter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLEQuoter>;
    deployContract(
      name: "IHLEALMState",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHLEALMState>;
    deployContract(
      name: "ICoreWriter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreWriter>;
    deployContract(
      name: "LendingModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LendingModule>;
    deployContract(
      name: "YieldOptimizer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldOptimizer>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "HLConstants",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLConstants>;
    deployContract(
      name: "HLConversions",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLConversions>;
    deployContract(
      name: "CoreWriterLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CoreWriterLib>;
    deployContract(
      name: "ICoreDepositWallet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreDepositWallet>;
    deployContract(
      name: "ICoreWriter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreWriter>;
    deployContract(
      name: "ITokenRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenRegistry>;
    deployContract(
      name: "PrecompileLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrecompileLib>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISovereignALM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignALM>;
    deployContract(
      name: "IFlashBorrower",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlashBorrower>;
    deployContract(
      name: "ISovereignPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignPool>;
    deployContract(
      name: "IValantisPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IValantisPool>;
    deployContract(
      name: "ISwapFeeModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModule>;
    deployContract(
      name: "ISwapFeeModuleMinimal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModuleMinimal>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ISovereignALM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignALM>;
    deployContract(
      name: "ISovereignOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignOracle>;
    deployContract(
      name: "IFlashBorrower",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFlashBorrower>;
    deployContract(
      name: "ISovereignPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignPool>;
    deployContract(
      name: "ISovereignPoolSwapCallback",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignPoolSwapCallback>;
    deployContract(
      name: "ISovereignVaultMinimal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISovereignVaultMinimal>;
    deployContract(
      name: "IValantisPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IValantisPool>;
    deployContract(
      name: "IVerifierModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifierModule>;
    deployContract(
      name: "SovereignPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SovereignPool>;
    deployContract(
      name: "ISwapFeeModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModule>;
    deployContract(
      name: "ISwapFeeModuleMinimal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapFeeModuleMinimal>;
    deployContract(
      name: "Constants",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Constants>;
    deployContract(
      name: "IHLEALM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHLEALM>;
    deployContract(
      name: "ILendingModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILendingModule>;
    deployContract(
      name: "ILendingOrchestrator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILendingOrchestrator>;
    deployContract(
      name: "IOracleModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IOracleModule>;
    deployContract(
      name: "IQuoteValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IQuoteValidator>;
    deployContract(
      name: "IYieldOptimizer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IYieldOptimizer>;
    deployContract(
      name: "L1OracleAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.L1OracleAdapter>;
    deployContract(
      name: "TwoSpeedEWMA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TwoSpeedEWMA>;
    deployContract(
      name: "YieldTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldTracker>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "HLEALM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLEALM>;
    deployContract(
      name: "HLEQuoter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HLEQuoter>;
    deployContract(
      name: "IHLEALMState",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHLEALMState>;
    deployContract(
      name: "ICoreWriter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreWriter>;
    deployContract(
      name: "LendingModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LendingModule>;
    deployContract(
      name: "YieldOptimizer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldOptimizer>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
